"""Bundle the small ES modules as a classic script so previews also open as file://."""
from pathlib import Path
import re
root=Path(__file__).resolve().parent
parts=[]
for filename in ['icons.js','catalog.js','views.js','app.js']:
 source=(root/filename).read_text()
 source=re.sub(r'^import .*?;\s*$', '', source, flags=re.M)
 source=re.sub(r'\bexport (?=(?:function|const|let|class)\b)', '', source)
 parts.append(f'// {filename}\n'+source)
(root/'bundle.js').write_text('/* Generated by build.py. Edit the source modules. */\n(()=>{\n'+ '\n'.join(parts)+'\n})();\n')
print('Built research-gallery/bundle.js')
